apiVersion: skaffold/v2beta19
kind: Config
deploy:
  kubectl:
    manifests:
      - "./infrastructure/k8s/**/*"
build:
  local:
    concurrency: 4
    # tryImportMissing: false
    # useBuildkit: false
    # useDockerCLI: false
    push: false

  # googleCloudBuild:
  #   projectId: ticketing-dev-323617

  artifacts:
    - image: ahmedelsharkawy/ticketing-authenticationservice
      context: apps/authentication
      docker:
        dockerfile: Dockerfile
        noCache: false
        squash: false
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: ahmedelsharkawy/ticketing-ticketsservice
      context: apps/tickets
      docker:
        dockerfile: Dockerfile
        noCache: false
        squash: false
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: ahmedelsharkawy/ticketing-ordersservice
      context: apps/orders
      docker:
        dockerfile: Dockerfile
        noCache: false
        squash: false
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: ahmedelsharkawy/ticketing-client
      context: apps/client
      docker:
        dockerfile: Dockerfile
        noCache: false
        squash: false
      sync:
        manual:
          - src: "**/*.js"
            dest: .
