apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
        - name: authentication
          image: ahmedelsharkawy/authenticationservice
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
