apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
        - name: authentication
          image: ahmedelsharkawy/ticketing-authenticationservice
          env:
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: ticket-app
                  key: JWT_SECRET_KEY
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-database
  template:
    metadata:
      labels:
        app: authentication-database
    spec:
      containers:
        - name: authentication-database
          image: mongo
