apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-database
  template:
    metadata:
      labels:
        app: authentication-database
    spec:
      containers:
        - name: authentication-database
          image: mongo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
        - name: authentication
          image: ahmedelsharkawy/ticketing-authenticationservice
          env:
            - name: MONGO_URL
              value: "mongodb://authentication-database:27017/authentication"
            - name: JWT_SECRET_KEY
              value: "ticketing-jwt-secret-key"
