apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: ahmedelsharkawy/ticketing-ticketsservice
          env:
            - name: MONGO_URL
              value: "mongodb://tickets-database:27017/tickets"
            - name: NATS_CLUSTER_ID
              value: "ticketing"
            - name: NATS_URL
              value: "http://nats:4222"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: ticket-app
                  key: JWT_SECRET_KEY
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets-database
  template:
    metadata:
      labels:
        app: tickets-database
    spec:
      containers:
        - name: tickets-database
          image: mongo
